In [2]:
import numpy as np

### tipos numéricos auxiliares

In [3]:
np.nan # not a number

nan

In [4]:
np.inf # infinito

inf

### repetidores

In [5]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [7]:
np.empty((1,2))

array([[  6.01334548e-154,   6.01347002e-154]])

In [8]:
A = np.array([[1, 2, 3, 4, 5]])
np.tile(A, (3, 1))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [9]:
np.tile(A.T, (2,4))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

### matriz identidade

In [10]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### transformadores

In [12]:
A = np.tile(np.array([[1, 2, 3, 4]]), (4, 1))
print(A)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [13]:
np.tril(A) # lower triangle of array

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

In [14]:
np.triu(A) # upper triangle of array

array([[1, 2, 3, 4],
       [0, 2, 3, 4],
       [0, 0, 3, 4],
       [0, 0, 0, 4]])

## creating an array with random numbers

### seed

In [15]:
np.random.seed(123456789)

# integer fed into random number generating algorithm
# manually seed  random number  generator if you need reproducibility

### np.random.randint(low,high,size)

In [19]:
coin = np.random.randint(0,2)
print(coin)

1


In [20]:
dice = np.random.randint(1,7)
print(dice)

5


In [18]:
np.random.random(size=5)
#np.random.random(size=x)

array([ 0.5341366 ,  0.50955304,  0.71356403,  0.25699895,  0.75269361])

In [21]:
np.random.rand() # draw a number  between 0 and 1

0.15489908253329554

In [22]:
np.random.seed(123456789)
P = 500
Q = 50
R = 1
A = np.random.randint(-10, 35, (500, 50))
X = np.random.randn(50, 1) * 10 + 3
B = np.random.randn(500, 1) * 3 + 10
A.shape, X.shape, B.shape

((500, 50), (50, 1), (500, 1))

### extra

In [ ]:
np.arange (start, finish, step)

In [23]:
np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [ ]:
np.linspace (start, finish, # of elements)

In [24]:
np.linspace (10, 20, 50)

array([ 10.        ,  10.20408163,  10.40816327,  10.6122449 ,
        10.81632653,  11.02040816,  11.2244898 ,  11.42857143,
        11.63265306,  11.83673469,  12.04081633,  12.24489796,
        12.44897959,  12.65306122,  12.85714286,  13.06122449,
        13.26530612,  13.46938776,  13.67346939,  13.87755102,
        14.08163265,  14.28571429,  14.48979592,  14.69387755,
        14.89795918,  15.10204082,  15.30612245,  15.51020408,
        15.71428571,  15.91836735,  16.12244898,  16.32653061,
        16.53061224,  16.73469388,  16.93877551,  17.14285714,
        17.34693878,  17.55102041,  17.75510204,  17.95918367,
        18.16326531,  18.36734694,  18.57142857,  18.7755102 ,
        18.97959184,  19.18367347,  19.3877551 ,  19.59183673,
        19.79591837,  20.        ])

In [3]:
#printing
print(np.arange(10000).reshape(100,100))
np.set_printoptions(threshold='nan')

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]
